version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    rebase-strategy: auto
    labels:
      - dependencies
      - auto
    commit-message:
      prefix: build
      include: scope
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    rebase-strategy: auto
    versioning-strategy: increase
    labels:
      - dependencies
      - auto
    commit-message:
      prefix: chore
      include: scope
