name: build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Read configs
        id: configs
        run: echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc)"
      - name: Setup node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: ${{ steps.configs.outputs.NODE_VERSION }}
      - name: Install packages
        run: npm i
      - name: Run tests
        run: npm test
      - name: Report coverage
        uses: Brightspace/third-party-actions@coverallsapp/github-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
